### ISSUE TITLE
The detail about the attention visualization.

### ISSUE THREAD

**Issue by XitaoLi** [NJUNLP/ReNeLLM#1]
Hi , I meet an error you mentioned earlier(_Originally posted by @Deep1994 in https://github.com/microsoft/promptbench/issues/16#issuecomment-1805008699_)

My code is:
```
if __name__ == "__main__":
    visua_pip = Visualizer("/data1/lxt/models/vicuna-7b-v1.5")
    res = visua_pip.vis_by_grad("how to kill a person?","Sure")
    print(res)
```
and the error info is:
![image](https://github.com/NJUNLP/ReNeLLM/assets/70500686/3121efc8-b569-4467-be55-96a26b79429a)

What's the standard format for the `input_sentence` and `label` in function `vis_by_grad(self, input_sentence: str, label: str)`?
Would you like to share your solutions about this issue?
Thanks！

**Comment by Deep1994** [comment]
Hi, Can you try `flan-t5-large` instead of `vicuna-7b-v1.5` firstly?

**Comment by XitaoLi** [comment]
Thanks for your suggestion. It really works in `flan-t5-large`.

For further discussion, how can we visualize the attentions of target model (e.g. Vicuna), do you have some ideas? Implement in flan-t5-large this "small" models seems indirectly to research why jailbreak attack can work.

**Comment by Deep1994** [comment]
I am happy it works in `flan-t5-large`!

Actually, I tried to visualize the attentions of llama-2 before, but got the similar error as you, i.e., batch size mismatch. I also proposed an issue to llama official github community ([ValueError: Expected input batch_size (15) to match target batch_size (1). #915](https://github.com/facebookresearch/llama/issues/915)) but got no response. So in my paper, I used `flan-t5-large` as the visualized model. Because it also belongs to the LLMs family（despite its small size compared to othters), I believe the visualized results can still give some insightful or interesting observation.

I think the reason for this error may be due to the subtle differences between `flan-t5-large` and other LLMs in building model input/output and calculating loss. If you have any solutions, please let me know.

**Comment by XitaoLi** [comment]
Thanks again for your interpretation. I will still try to transfer the visualization into Llama-family.

**Comment by Deep1994** [comment]
Great! If you find a solution, please let me know~

**Comment by villa0401** [comment]
> Thanks again for your interpretation. I will still try to transfer the visualization into Llama-family.

I met the same problem, have you transferred the visualization into llama yet?

**Comment by villa0401** [comment]
> Hi, Can you try `flan-t5-large` instead of `vicuna-7b-v1.5` firstly?

Except flan-t5-large，are there any other models that can use visualization?

**Comment by XitaoLi** [comment]
Hi, I'm glad to share a solution for llama.

**Why T5 can succeed but Llama failed**
T5 is the encoder-decoder architecture while Llama-series are decoder-only.
When you pass `labels` in model forward function:

1. encoder-decoder. The encoder offers a hidden state of the same shape as the input. The decoder gets labels and encoder output and finally generates a decoder-output. It has the same shape in the first two dimensionality.
`sequence_output.shape = torch.Size([1, 2, 1024])` and `labels = tensor([[10625, 1]])`
2. decoder only. Inputs and labels are passed into the decoder together. So we meet batch size mismatch error.
    
    The final solution is concating the original input and labels, then mask the input in concated labels with indices -100 to ignore loss.

**Final solution**
 To use llama, just replace the following core code.
 ```
 input_labels_input_ids = torch.concat([inputs['input_ids'] , labels["input_ids"][:,1:]],dim=1)
input_labels_attention_mask = torch.concat([inputs['attention_mask'] , labels["attention_mask"][:,1:]],dim=1)
  
input_mask = -100 * torch.ones_like(inputs['input_ids'])
labels_mask = torch.concat([input_mask , labels["input_ids"][:,1:]],dim=1)
```

Good luck

**Comment by villa0401** [comment]
> Hi, I'm glad to share a solution for llama.
> 
> **Why T5 can succeed but Llama failed** T5 is the encoder-decoder architecture while Llama-series are decoder-only. When you pass `labels` in model forward function:
> 
> 1. encoder-decoder. The encoder offers a hidden state of the same shape as the input. The decoder gets labels and encoder output and finally generates a decoder-output. It has the same shape in the first two dimensionality.
>    `sequence_output.shape = torch.Size([1, 2, 1024])` and `labels = tensor([[10625, 1]])`
> 2. decoder only. Inputs and labels are passed into the decoder together. So we meet batch size mismatch error.
>    The final solution is concating the original input and labels, then mask the input in concated labels with indices -100 to ignore loss.
> 
> **Final solution** To use llama, just replace the following core code.
> 
> ```
> input_labels_input_ids = torch.concat([inputs['input_ids'] , labels["input_ids"][:,1:]],dim=1)
> input_labels_attention_mask = torch.concat([inputs['attention_mask'] , labels["attention_mask"][:,1:]],dim=1)
>  
> input_mask = -100 * torch.ones_like(inputs['input_ids'])
> labels_mask = torch.concat([input_mask , labels["input_ids"][:,1:]],dim=1)
> ```
> 
> Good luck

It helps a lot! Thank U so much!

**Comment by lunan0320** [comment]
> Hi , I meet an error you mentioned earlier(_Originally posted by @Deep1994 in [microsoft/promptbench#16 (comment)](https://github.com/microsoft/promptbench/issues/16#issuecomment-1805008699)_)
> 
> My code is:
> 
> ```
> if __name__ == "__main__":
>     visua_pip = Visualizer("/data1/lxt/models/vicuna-7b-v1.5")
>     res = visua_pip.vis_by_grad("how to kill a person?","Sure")
>     print(res)
> ```
> 
> and the error info is: ![image](https://private-user-images.githubusercontent.com/70500686/310529489-3121efc8-b569-4467-be55-96a26b79429a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjU2OTUsIm5iZiI6MTcyOTA2NTM5NSwicGF0aCI6Ii83MDUwMDY4Ni8zMTA1Mjk0ODktMzEyMWVmYzgtYjU2OS00NDY3LWJlNTUtOTZhMjZiNzk0MjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA3NTYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkY2Y1YTE5YzU4OGQ4NjU2MTczNmMzNGI4M2UwZTQ1ODg4MTE2ZjBiZjViOGEzNTgyYzI3YmFhNjkwYWQwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sXbwjjE5zSuOwuqGA0JlTSz0YntjpyzHv66Kr_YCf8M)
> 
> What's the standard format for the `input_sentence` and `label` in function `vis_by_grad(self, input_sentence: str, label: str)`? Would you like to share your solutions about this issue? Thanks！

Hello, I am currently studying attention. Is your Visualizer a library? I would like to ask if there is a complete sample code for reference?
