### ISSUE TITLE
Support for Ollama 

### ISSUE THREAD

**Issue by tanmaymittal** [NJUNLP/ReNeLLM#3]
Hi I was wondering if there is currently a way to use this with an llm running locally on my machine instead of having to use chatgpt or claude APIs. Ollama has a few different llms, perhaps there is a way to generalize is, giving people the freedom to test against more models.

**Comment by Deep1994** [comment]
Hi, 

Thank you for your interest in our work. Indeed, we used `gpt-3.5-turbo` and `claude-2` as harmful classifiers and model under test respectively in our paper, but in fact you can use any model you want to use to achieve these two purposes. We will support open source LLMs in the future, please stay tuned.
