### ISSUE TITLE
Generating the final jailbreak prompt without openai API key and anthropic API key.

### ISSUE THREAD

**Issue by tjumc** [NJUNLP/ReNeLLM#5]
Thanks for your interesting work, I want to generate some final jailbreak prompts for test, but I don't have openai API key and anthropic API key.
Are there any other ways (like locally available models) to solve this problem?

**Comment by Deep1994** [comment]
Hi! Without an API key, you can use open-source models (such as LLaMA 3) to rewrite prompts. You can modify them based on the ReNeLLM code.
