### ISSUE TITLE
能给出你给520条数据按7个场景分类后的数据集吗？非常感谢

### ISSUE THREAD

**Issue by maoxuxu** [NJUNLP/ReNeLLM#6]

**Comment by Deep1994** [comment]
[gpt-4_single_round_prompt_annotation.json](https://github.com/user-attachments/files/17931587/gpt-4_single_round_prompt_annotation.json)
你好，我上传了520条数据按7个场景分类后的结果，结果文件中"idx"字段对应Advbench中的同样idx的样本，分类采用的prompt以及每个分类结果代表的有害场景可以在我们论文的 Table 10 中找到。

需要注意的是，分类结果中GPT-4将520条数据分成了10类，但有3类的样本数非常少，为了便于统计和分析，我们人工检查之后合并了这部分类别，最终得到了7个分类场景。具体的类别合并信息如下：1 -> 0，8 ->9，11 -> 6，最终可以归为7类：0, 2, 3, 4, 5 , 6, 9。您可以按照如上规则处理结果文件，即可得到跟我们论文中一致的分类结果。

如果有任何其他问题，欢迎随时提问~

**Comment by maoxuxu** [comment]
非常感谢您！
